import mongoose from "mongoose";

const appraisalSchema = new mongoose.Schema(
  {
    Appraise: { type: String },
    branch: { type: String },
    Jobtitle: { type: String },
    Appraiser: { type: String },
    currentposition: { type: String },
    CompletionDate: { type: String },
    CompletionTime: { type: String },
    responsibilitiesDuties: { type: String },
    partsJob: { type: String },
    rows: { type: Array, default: [] },
    TechnicalScore: { type: String },
    TechnicalCom: { type: String },
    LegalBestScore: { type: String },
    LegalBestCom: { type: String },
    CustomerRelationsScore: { type: String },
    CustomerRelationsCom: { type: String },
    TimeManagementScore: { type: String },
    TimeManagementCom: { type: String },
    CostControlScore: { type: String },
    CostControlCom: { type: String },
    ReportingAdministrationScore: { type: String },
    ReportingAdministrationCom: { type: String },
    CommunicationSkillsScore: { type: String },
    CommunicationSkillsCom: { type: String },
    DelegationSkillsScore: { type: String },
    DelegationSkillsCom: { type: String },
    ITScore: { type: String },
    ITCom: { type: String },
    AbilityScore: { type: String },
    AbilityCom: { type: String },
    ProblemScore: { type: String },
    ProblemCom: { type: String },
    TeamScore: { type: String },
    TeamCom: { type: String },
    EnergyScore: { type: String },
    EnergyCom: { type: String },
    SteadinessScore: { type: String },
    SteadinessCom: { type: String },
    AdaptabilityScore: { type: String },
    AdaptabilityCom: { type: String },
    PersonalScore: { type: String },
    PersonalCom: { type: String },
    specifyScore: { type: String },
    specifyCom: { type: String },
    particularproblems: { type: String },
    lastappraisal: { type: String },
    furthertraining: { type: String },
    lacktraining: { type: String },
    trainingcoaching: { type: String },
    productivitycompliance: { type: String },
    achieveambition: { type: String },
    yourappraiser: { type: String },
    CurrentBusiness: { type: String },
    Recordgathered: { type: String },
    rows1: { type: Array, default: [] },
    TechnicalScore1: { type: String },
    TechnicalCom1: { type: String },
    LegalBestScore1: { type: String },
    LegalBestCom1: { type: String },
    CustomerRelationsScore1: { type: String },
    CustomerRelationsCom1: { type: String },
    TimeManagementScore1: { type: String },
    TimeManagementCom1: { type: String },
    CostControlScore1: { type: String },
    CostControlCom1: { type: String },
    ReportingAdministrationScore1: { type: String },
    ReportingAdministrationCom1: { type: String },
    CommunicationSkillsScore1: { type: String },
    CommunicationSkillsCom1: { type: String },
    DelegationSkillsScore1: { type: String },
    DelegationSkillsCom1: { type: String },
    ITScore1: { type: String },
    ITCom1: { type: String },
    AbilityScore1: { type: String },
    AbilityCom1: { type: String },
    ProblemScore1: { type: String },
    ProblemCom1: { type: String },
    TeamScore1: { type: String },
    TeamCom1: { type: String },
    EnergyScore1: { type: String },
    EnergyCom1: { type: String },
    SteadinessScore1: { type: String },
    SteadinessCom1: { type: String },
    AdaptabilityScore1: { type: String },
    AdaptabilityCom1: { type: String },
    PersonalScore1: { type: String },
    PersonalCom1: { type: String },
    specifyScore1: { type: String },
    specifyCom1: { type: String },
    Appraiseeimprove: { type: String },
    DevelopmentTraining: { type: String },
    JobDescription: { type: String },
    Appraiserscomments: { type: String },
    Appraiseecomments: { type: String },
    SignatureAppraisee: { type: String },
    SignatureAppraiser: { type: String },
    Name: { type: String },
    rows2: { type: Array, default: [] },
  },
  { timestamps: true }
);

export default mongoose.model("Appraisal", appraisalSchema);
