import mongoose from "mongoose";
const safeSchema = new mongoose.Schema(
  {
    serviceuser: { type: String },
    branch: { type: String },

    address: { type: String },
    Mobile: { type: String },
    CarepurchasedPrivately: { type: String },
    Carepackage: { type: String },
    managerforassessment: { type: String },
    caresupportplan: { type: String },
    informationrequire: { type: String },
    contactoffice: { type: String },
    courteousreply: { type: String },
    promptlysympatheticall: { type: String },
    happywithservice: { type: String },
    difficultservice: { type: String },
    Careplanuptodate: { type: String },
    workersarrivetime: { type: String },
    wearuniform: { type: String },
    identitybadges: { type: String },
    allocatedtime: { type: String },
    dutiessatisfaction: { type: String },
    workerscourteous: { type: String },
    Supportworkerexpect: { type: String },
    workerallocatedtimes: { type: String },
    makecomplaint: { type: String },
    fearrecrimination: { type: String },
    evercomplaint: { type: String },
    remainconfidential: { type: String },
    ReportBook: { type: String },
    recommendPBLCare: { type: String },
    correctinvoices: { type: String },
    invoicedetailseasily: { type: String },
    queryinvoice: { type: String },
    dealtpromptly: { type: String },
    Generalcomments: { type: String },
    ActionPlans: { type: String },
    RepresentativeSigDate: { type: String },
    ManagerSignatureDate: { type: String },
  },
  { timestamps: true }
);

export default mongoose.model("Safe", safeSchema);
